In [1]:
import torch
import torch.nn as nn
from collections import OrderedDict
import matplotlib.pyplot as plt

model = nn.Sequential(OrderedDict([
    ('hidden', nn.Linear(2, 4)),  # first hidden layer with 4 neurons
    ('sigmoid', nn.Sigmoid()),    # sigmoid activation function
    ('output', nn.Linear(4, 1)),  # output layer with 1 neuron
    ('sigmoid', nn.Sigmoid())     # sigmoid activation function
]))
print(model)

data_in = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float)
print(data_in)

data_target = torch.tensor([[0], [1], [1], [0]], dtype=torch.float)
print(data_target)

criterion = nn.BCEWithLogitsLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

# train the model
losses = []
for epoch in range(10000):
    # reset the gradients to zero before each forward and backward pass
    optimizer.zero_grad()    
    outputs = model(data_in) # forward pass
    loss = criterion(outputs, data_target) # calculate loss
    loss.backward()          # backward pass
    optimizer.step()         # update weights
    losses.append(loss.item())
    predicted_classes = (outputs.round() == data_target)
    accuracy = predicted_classes.sum().item() / len(data_target)
    if accuracy == 1:
        print(f"Model reached 100% accuracy at epoch {epoch+1}")
        break

# model accuracy
predicted = torch.round(outputs)
correct = (predicted == data_target).sum()
total = data_target.size(0)
accuracy = correct / total
print(f'Model Accuracy: {accuracy}%')    

# visualize the resuts

# print the best one of the weights for each layer
print(f"Model weights:")
for name, param in model.named_parameters():
    if param.requires_grad:
        print(name, param.data)
        print(name, torch.max(param.data))

Sequential(
  (hidden): Linear(in_features=2, out_features=4, bias=True)
  (sigmoid): Sigmoid()
  (output): Linear(in_features=4, out_features=1, bias=True)
)
tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])
tensor([[0.],
        [1.],
        [1.],
        [0.]])
Model Accuracy: 0.0%
Model weights:
hidden.weight tensor([[ 5.0780, -6.6407],
        [ 1.7465, -0.3915],
        [-4.3058, -4.7499],
        [-6.0630,  3.8577]])
hidden.weight tensor(5.0780)
hidden.bias tensor([-2.3440,  0.4583,  1.0669, -1.5124])
hidden.bias tensor(1.0669)
output.weight tensor([[ 9.0624, -2.1759, -5.4511,  8.4026]])
output.weight tensor(9.0624)
output.bias tensor([-2.1479])
output.bias tensor(-2.1479)


In [2]:
import torch
import torch.nn as nn
from collections import OrderedDict
import matplotlib.pyplot as plt

model1 = nn.Sequential(OrderedDict([
    ('hidden', nn.Linear(2, 3)),  # first hidden layer with 3 neurons
    ('sigmoid', nn.Sigmoid()),    # sigmoid activation function
    ('output', nn.Linear(3, 2)),  # output layer with 2 neurons
    ('sigmoid', nn.Sigmoid())     # sigmoid activation function
]))
print(model1)

data_in1 = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float)
print(data_in1)

data_target1 = torch.tensor([[0, 0], [0, 1], [0, 1], [1, 0]], dtype=torch.float)
print(data_target1)

criterion1 = nn.MSELoss()
optimizer1 = torch.optim.SGD(model1.parameters(), lr=0.1)

# train the model
losses1 = []
for epoch in range(10000):
    # reset the gradients to zero before each forward and backward pass
    optimizer1.zero_grad()  
    # forward pass
    outputs1 = model1(data_in1)
    # calculate loss
    loss1 = criterion1(outputs1, data_target1)
    # backward pass
    loss1.backward()          
    # update weights
    optimizer1.step()         
    losses1.append(loss1.item())
    
    # accuracy
    predicted_classes1 = (outputs1.round() == data_target1)
    accuracy1 = predicted_classes1.sum().item() / len(data_target1)
    if accuracy1 == 1:
        print(f"Model 1 reached 100% accuracy at epoch {epoch+1}")
        break
        
        
# visualize the resuts
predicted = torch.round(outputs1)
correct = (predicted == data_target1).sum()
total = data_target1.size(0)
accuracy = correct / total
print(f'Model Accuracy: {accuracy}%')  

    
# print model wights
print(f"Model weights:")
for name, param in model1.named_parameters():
    if param.requires_grad:
        print(name, param.data)

Sequential(
  (hidden): Linear(in_features=2, out_features=3, bias=True)
  (sigmoid): Sigmoid()
  (output): Linear(in_features=3, out_features=2, bias=True)
)
tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.]])
Model 1 reached 100% accuracy at epoch 16
Model Accuracy: 1.0%
Model weights:
hidden.weight tensor([[-0.1591, -0.1238],
        [ 0.7153, -0.0021],
        [ 0.6530, -0.4382]])
hidden.bias tensor([ 0.5856,  0.3858, -0.2994])
output.weight tensor([[ 0.5383,  0.3788, -0.1214],
        [ 0.2268,  0.3535, -0.1654]])
output.bias tensor([-0.2853,  0.1890])


In [3]:
import torch
import torch.nn as nn
from collections import OrderedDict
import matplotlib.pyplot as plt

model1 = nn.Sequential(OrderedDict([
    ('hidden', nn.Linear(2, 3)),  # first hidden layer with 3 neurons
    ('ReLU', nn.ReLU()),          # relu activation function
    ('output', nn.Linear(3, 2)),  # output layer with 3 neurons
    ('sigmoid', nn.Sigmoid())     # sigmoid activation function
]))
print(model1)

data_in1 = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float)
print(data_in1)

data_target1 = torch.tensor([[0, 0], [0, 1], [0, 1], [1, 0]], dtype=torch.float)
print(data_target1)

criterion1 = nn.MSELoss()
optimizer1 = torch.optim.SGD(model1.parameters(), lr=0.1)

# train the model
losses1 = []
for epoch in range(1000):
    # reset the gradients to zero before each forward and backward pass
    optimizer1.zero_grad()    
    outputs1 = model1(data_in1) # forward pass
    loss1 = criterion1(outputs1, data_target1) # calculate loss
    loss1.backward()          # backward pass
    optimizer1.step()         # update weights
    losses1.append(loss1.item())
    predicted_classes1 = (outputs1.round() == data_target1)
    accuracy1 = predicted_classes1.sum().item() / len(data_target1)
    if accuracy1 == 1:
        print(f"Model 1 reached 100% accuracy at epoch {epoch+1}")
        break
        
# visualize the results
print(outputs1)
predicted = torch.round(outputs1)
correct = (predicted == data_target1).sum()
total = data_target1.size(0)
accuracy = correct / total
print(f'Model Accuracy: {accuracy}%') 

# print model wights
print(f"Model weights:")
for name, param in model1.named_parameters():
    if param.requires_grad:
        print(name, param.data)

Sequential(
  (hidden): Linear(in_features=2, out_features=3, bias=True)
  (ReLU): ReLU()
  (output): Linear(in_features=3, out_features=2, bias=True)
  (sigmoid): Sigmoid()
)
tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.]])
tensor([[0.2543, 0.5003],
        [0.2543, 0.5003],
        [0.2543, 0.5003],
        [0.2543, 0.5003]], grad_fn=<SigmoidBackward0>)
Model Accuracy: 1.25%
Model weights:
hidden.weight tensor([[ 0.3944, -0.4629],
        [ 0.2585, -0.3613],
        [-0.6173, -0.0433]])
hidden.bias tensor([-0.6005, -0.3915, -0.6767])
output.weight tensor([[-0.3950,  0.5048,  0.1939],
        [-0.2349,  0.4272,  0.5702]])
output.bias tensor([-1.0761,  0.0012])


In [4]:
import torch
import torch.nn as nn
from collections import OrderedDict
import matplotlib.pyplot as plt

model1 = nn.Sequential(OrderedDict([
    ('hidden', nn.Linear(2, 3)),  # first hidden layer with 3 neurons
    ('ReLU', nn.ReLU()),          # relu activation function
    ('output', nn.Linear(3, 2)),  # output layer with 3 neurons
    ('tanh', nn.Tanh())     # sigmoid activation function
]))
print(model1)

data_in1 = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float)
print(data_in1)

data_target1 = torch.tensor([[0, 0], [0, 1], [0, 1], [1, 0]], dtype=torch.float)
print(data_target1)

criterion1 = nn.MSELoss()
optimizer1 = torch.optim.SGD(model1.parameters(), lr=0.1)

# train the model
losses1 = []
for epoch in range(1000):
    # reset the gradients to zero before each forward and backward pass
    optimizer1.zero_grad()    
    outputs1 = model1(data_in1) # forward pass
    loss1 = criterion1(outputs1, data_target1) # calculate loss
    loss1.backward()          # backward pass
    optimizer1.step()         # update weights
    losses1.append(loss1.item())
    predicted_classes1 = (outputs1.round() == data_target1)
    accuracy1 = predicted_classes1.sum().item() / len(data_target1)
    if accuracy1 == 1:
        print(f"Model 1 reached 100% accuracy at epoch {epoch+1}")
        break

# visualize the resuts
print(outputs1)
predicted = torch.round(outputs1)
correct = (predicted == data_target1).sum()
total = data_target1.size(0)
accuracy = correct / total
print(f'Model Accuracy: {accuracy}%') 

# print model wights
print(f"Model weights:")
for name, param in model1.named_parameters():
    if param.requires_grad:
        print(name, param.data)

Sequential(
  (hidden): Linear(in_features=2, out_features=3, bias=True)
  (ReLU): ReLU()
  (output): Linear(in_features=3, out_features=2, bias=True)
  (tanh): Tanh()
)
tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.]])
tensor([[0.0028, 0.5040],
        [0.0028, 0.5040],
        [0.0023, 0.9361],
        [0.9411, 0.0023]], grad_fn=<TanhBackward0>)
Model Accuracy: 1.75%
Model weights:
hidden.weight tensor([[ 0.8790, -0.8751],
        [ 0.5926, -0.4622],
        [ 1.1611,  0.8714]])
hidden.bias tensor([-0.0036, -0.0012, -0.8758])
output.weight tensor([[-0.5105,  0.0285,  1.5065],
        [ 0.9976,  0.7401, -0.5606]])
output.bias tensor([0.0028, 0.5546])
